[project]
name = "ind320-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M03ZGH", email = "moezyadgar03@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "pygments>=2.21.0",
    "streamlit>=1.63.0",
]

[project.scripts]
ind320-app = "ind320_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
